### ISSUE TITLE
backend sources

### ISSUE THREAD

**Issue by x0rzkov** [tralves/groceries-ns-vue#30]
Hi,

Hope you are all well !

Can we have access to the code for the backend service ?
https://github.com/x0rzkov/groceries-ns-vue/blob/master/app/services/BackendService.js#L10-L13

Thanks in advance.

Cheers,
X

**Comment by tralves** [comment]
Hi!

The app is using the kinvey backend service (see https://www.progress.com/kinvey). It's a service that you can use so you don't need to implement a backend. It's a paid service (not very expensive, though) and I am using it there because the company behind Kinvey is also behind NativeScript.

There are other alternatives such as Firebase that also work well with NativeScript. Depending on your app, it may be best to use one of these solutions instead of developing your own.

Hope it helps!

**Comment by x0rzkov** [comment]
Thanks for your reply but can we have the schema at least to reproduce the backend object to send ?
